services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-claude
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-claude
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - prometheus

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter-claude
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    networks:
      - monitoring
    restart: unless-stopped

  mcp-grafana:
    image: mcp/grafana:latest
    container_name: mcp-grafana-claude
    ports:
      - "3001:3001"
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_SERVICE_ACCOUNT_TOKEN=${GRAFANA_SERVICE_ACCOUNT_TOKEN:-}
      - GRAFANA_USERNAME=${GRAFANA_USERNAME:-admin}
      - GRAFANA_PASSWORD=${GRAFANA_PASSWORD:-admin}
    command:
      - "-transport"
      - "sse"
      - "-address"
      - "0.0.0.0:3001"
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - grafana

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
